# This YAML file shows how to deploy the volume-data-source-validator controller

# The volume-data-source-validator controller does asynchronous validation of PVC data
# sources.
# It should be installed as part of the base Kubernetes distribution in an appropriate
# namespace for components implementing base system functionality. For installing with
# Vanilla Kubernetes, kube-system makes sense for the namespace.

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: volume-data-source-validator
  namespace: kube-system
spec:
  serviceName: volume-data-source-validator
  replicas: 1
  selector:
    matchLabels:
      app: volume-data-source-validator
  template:
    metadata:
      labels:
        app: volume-data-source-validator
    spec:
      serviceAccount: volume-data-source-validator
      containers:
        - name: volume-data-source-validator
          image: registry.k8s.io/sig-storage/volume-data-source-validator:v1.0.0
          args:
            - "--v=5"
            - "--leader-election=false"
            - "--http-endpoint=:8080"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http-endpoint
              protocol: TCP
